import { fireEvent, render, screen, waitFor } from '@testing-library/react'
import { beforeEach, describe, expect, it, vi } from 'vitest'

const gmail = vi.hoisted(() => ({ availability: vi.fn(), list: vi.fn(), connect: vi.fn(), labels: vi.fn(), bind: vi.fn(), disconnect: vi.fn(), schedule: vi.fn(), updateSchedule: vi.fn(), syncNow: vi.fn() }))
vi.mock('../../platform', async (original) => ({ ...await original<typeof import('../../platform')>(), platformClient: { runtime: 'tauri', getGmailAvailability: gmail.availability, listGmailConnections: gmail.list, connectGmail: gmail.connect, listGmailLabels: gmail.labels, bindGmailLabel: gmail.bind, disconnectGmail: gmail.disconnect, getGmailSchedule: gmail.schedule, updateGmailSchedule: gmail.updateSchedule, syncGmailNow: gmail.syncNow } }))
vi.mock('./gmailSyncEventPlatform', () => ({ gmailSyncEventPlatform: { subscribe: vi.fn().mockResolvedValue(() => undefined) } }))
import { GmailSettingsPanel } from './GmailSettingsPanel'

const timestamp = '2026-07-15T00:00:00Z'
const selecting = { id: 'gmail-1', status: 'SELECTING_LABEL' as const, accountEmail: 'home@example.com', labelId: null, labelName: null, gmailQuery: 'has:attachment', labelBound: false, lastFullScanAt: null, lastChangeAt: null, createdAt: timestamp, updatedAt: timestamp }
const connected = { ...selecting, status: 'CONNECTED' as const, labelId: 'Label_1', labelName: 'KakeFlow', labelBound: true }
const schedule = { connectionId: 'gmail-1', enabled: true, intervalMinutes: 30 as const, nextDueAt: timestamp, running: false, lastResult: 'NO_CHANGES' as const, lastDiscoveredCount: 0, consecutiveFailures: 0, suspendedUntil: null, suspensionReason: null, lastErrorCode: null, updatedAt: timestamp }

describe('GmailSettingsPanel', () => {
  beforeEach(() => { vi.clearAllMocks(); gmail.availability.mockResolvedValue({ available: true, authorizationMode: 'SYSTEM_BROWSER_LOOPBACK', scopeProfile: 'GMAIL_READONLY', unavailableReason: null }); gmail.list.mockResolvedValue([]); gmail.connect.mockResolvedValue(selecting); gmail.labels.mockResolvedValue([{ id: 'Label_1', name: 'KakeFlow', kind: 'USER' }]); gmail.bind.mockResolvedValue(connected); gmail.schedule.mockResolvedValue(schedule); gmail.updateSchedule.mockResolvedValue(schedule); gmail.syncNow.mockResolvedValue({ ...schedule, lastResult: 'DISCOVERED', lastDiscoveredCount: 2 }); gmail.disconnect.mockResolvedValue({ ...connected, status: 'DISCONNECTED' }) })
  it('authorizes then binds a bounded attachment label without auto-posting', async () => { render(<GmailSettingsPanel householdId="family" />); fireEvent.click(await screen.findByRole('button', { name: 'Gmail を接続' })); await waitFor(() => expect(gmail.labels).toHaveBeenCalledWith('family', 'gmail-1')); expect(screen.getByText(/メール添付は自動記帳されません/)).toBeInTheDocument(); fireEvent.click(await screen.findByRole('button', { name: 'ラベルを接続' })); await waitFor(() => expect(gmail.bind).toHaveBeenCalledWith({ householdId: 'family', connectionId: 'gmail-1', labelId: 'Label_1', labelName: 'KakeFlow', gmailQuery: 'has:attachment' })); expect(await screen.findByText(/添付メールは確認待ち/)).toBeInTheDocument() })
  it('updates schedule, syncs and disconnects while preserving evidence', async () => { gmail.list.mockResolvedValue([connected]); render(<GmailSettingsPanel householdId="family" />); const interval = await screen.findByLabelText('Gmail 同期間隔'); fireEvent.change(interval, { target: { value: '60' } }); fireEvent.click(screen.getByRole('button', { name: 'スケジュールを保存' })); await waitFor(() => expect(gmail.updateSchedule).toHaveBeenCalledWith({ householdId: 'family', connectionId: 'gmail-1', enabled: true, intervalMinutes: 60 })); fireEvent.click(screen.getByRole('button', { name: '今すぐ同期' })); expect(await screen.findByText(/2件の新しいメール候補/)).toBeInTheDocument(); fireEvent.click(screen.getByRole('button', { name: '接続を解除' })); expect(await screen.findByText(/取り込み済みの原本と台帳は残ります/)).toBeInTheDocument() })
})
